Repository ucsb-cs156-f22/f22-5pm-courses, pull requests merged in 2022-11, with the labels that each got.

#9 glt - Update brand to UCSB Courses Search
  frontend/src/main/components/Nav/AppNavbar.js
Labels: 5, f22-5pm-2

#10 bh - Restrict name for Personal Schedule to 15 chars or less
  frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js
Labels: 5, f22-5pm-2

#14 ilj - Switch section search & description search
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/CourseDescriptions/CourseDescriptionIndexPage.js
  frontend/src/main/pages/SectionSearches/SectionSearchesIndexPage.js
  frontend/src/stories/pages/HomePage/CourseDescriptions/CourseDescriptionIndexPage.stories.js
  frontend/src/stories/pages/HomePage/HomePage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/CourseDescriptions/CourseDescriptionIndexPage.test.js
Labels: 10, f22-5pm-1

#13 Gianmarco/Ethan/Christian - added string sourceRepo to systemInfo class and added initialization in application.properties
  src/main/java/edu/ucsb/cs156/courses/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/courses/services/SystemInfoServiceImpl.java
  src/main/resources/application.properties
Labels: f22-5pm-1

#33 my - BACKEND - personal schedules must have unique name and quarter
  src/main/java/edu/ucsb/cs156/courses/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesController.java
  src/main/java/edu/ucsb/cs156/courses/repositories/PersonalScheduleRepository.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesControllerTests.java
Labels: 10, f22-5pm-2

#21 glt - Adjust post method for `/api/courses/post` to prohibit adding primaries that have multiple secondaries
  pom.xml
  src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/documents/SectionFixtures.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: f22-5pm-2, FIXME: Peer CR

#12 bh - Adding backend functionality for name 15 char limit in personal schedule
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesControllerTests.java
Labels: 10, f22-5pm-2

#42 LPN - copied Quarter files from old courses
  src/main/java/edu/ucsb/cs156/courses/models/Quarter.java
  src/test/java/edu/ucsb/cs156/courses/models/QuarterTests.java
Labels: 10, f22-5pm-1

#34 Modify footer to take value of source repo from /api/systemInfo inste…
  frontend/src/fixtures/systemInfoFixtures.js
  frontend/src/main/components/Nav/Footer.js
  frontend/src/main/layouts/BasicLayout/BasicLayout.js
  frontend/src/tests/components/Nav/Footer.test.js
Labels: 10, f22-5pm-1

#39 sc - create personal schedules dropdown component
  frontend/src/fixtures/personalScheduleFixtures.js
  frontend/src/main/components/PersonalSchedules/PersonalScheduleDropdown.js
  frontend/src/stories/components/PersonalSchedules/PersonalScheduleDropdown.stories.js
  frontend/src/tests/components/PersonalSchedules/PersonalScheduleDropdown.test.js
Labels: f22-5pm-2, STAFF: ready for review

#43 Ethan - Add frontend components for the course-over-time search
  frontend/src/main/components/BasicCourseSearch/CourseOverTimeSearchForm.js
  frontend/src/stories/components/BasicCourseSearch/CourseOverTimeSearchForm.stories.js
  frontend/src/tests/components/BasicCourseSearch/CourseOverTimeSearchForm.test.js
Labels: f22-5pm-1, STAFF: ready for review

#48 IH: Add query & controller for course-over-time search
  src/main/java/edu/ucsb/cs156/courses/collections/ConvertedSectionCollection.java
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeControllerTests.java
Labels: 20, f22-5pm-1

#49 Peter - Add PersonalSections Table to PersonalSchedulesDetails Page
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesDetailsPage.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesDetailsPage.test.js
Labels: 10, f22-5pm-2

#50 James backend quartersubjects
  .env.SAMPLE
  src/main/java/edu/ucsb/cs156/courses/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataWithQuarterJob.java
  src/main/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataWithQuarterJobFactory.java
  src/test/java/edu/ucsb/cs156/courses/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataWithQuarterJobFactoryTests.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataWithQuarterJobTests.java
Labels: 20, f22-5pm-1
