Repository ucsb-cs156-f22/f22-5pm-courses, pull requests merged in 2022-12, with the labels that each got.

#51 Gianmarco - Fixes UI bug where first use of update courses job fails
  frontend/src/main/components/Jobs/UpdateCoursesJobForm.js
Labels: f22-5pm-1, STAFF: ready for review

#54 IH - Add Course-Over-Time search page, & Section-Over-Time table
  frontend/src/App.js
  frontend/src/fixtures/sectionOverTimeFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Sections/SectionsOverTimeTable.js
  frontend/src/main/components/SectionsOverTimeTableBase.js
  frontend/src/main/pages/CourseOverTime/CourseOverTimeIndexPage.js
  frontend/src/stories/components/Sections/SectionOverTimeTable.stories.js
  frontend/src/stories/pages/CourseOverTimeIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Sections/SectionsOverTimeTable.test.js
  frontend/src/tests/components/SectionsOverTimeTableBase.test.js
  frontend/src/tests/pages/CourseOverTime/CourseOverTimeIndexPage.test.js
Labels: 10, f22-5pm-1

#55 lpn - fixed staff typo and modified Quarter list function
  src/main/java/edu/ucsb/cs156/courses/models/Quarter.java
  src/test/java/edu/ucsb/cs156/courses/models/QuarterTests.java
Labels: 10, f22-5pm-1

#47 bh - better error message in frontend for duplicate personal schedule creation
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesCreatePage.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesCreatePage.test.js
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesControllerTests.java
Labels: 10, f22-5pm-2

#53 kd - issue #45: ensured uniqueness for PSCourse post. Added tests.
  src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java
Labels: 10, f22-5pm-2
